services:
  web:
    volumes:
      - ../:/home/UserRepo
      - ../hugo.toml:/home/CentralRepo/hugo.toml
#    working_dir: /var/www/html
    command: >
      sh -c "hugo server --bind 0.0.0.0 --port 8080"  
